language: java
jdk: oraclejdk8
sudo: required
env:
  global:
    - POSTGRES_PORT=5431
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo sed -i 's/port = 5433/port = 5431/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
addons:
  postgresql: '11'
  apt:
    packages:
      - postgresql-11
      - postgresql-client-11

  
