version: '3.1'

services:

  db:
    build: ./database/
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5431:5432